plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs32.github.io 
baseurl: "/f19"

course: "CS32"
qtr: "F19"
quarter: "Fall 2019"
piazza_url: piazza.com/ucsb/fall2019/cmpsc32/home
gauchospace_course_page:
gradescope_class_url: https://www.gradescope.com/courses/65495

ta_list: "Yaoyi, Robert"
ta_list_full: "Yaoyi Bai, Robert McLaughlin"
mentors_list: "Arthur Gatin, Helen Huang, Jacqueline Mai, Alan Roddick"
discussion_section_times: "9am, 10am, 11am, 12pm"

github_url: https://github.com/ucsb-cs32/f19
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

submit_cs_course:

start_week: 0
start_date: 2019-09-22 00:00:00.00-7:00
num_weeks: 11
extra_exam_week: true
sections: "9am, 10am, 11am, 12pm"

cal_dates: >
  [
  {"label":"First day of Fall Quarter", "date":"2019-09-26" },
  {"label":"Univ Holiday: Veterans' Day", "date":"2019-11-11" },
  {"label":"Univ Holiday: Thanksgiving Break", "date":"2019-11-28" },
  {"label":"Univ Holiday: Thanksgiving Break", "date":"2019-11-29" },
  {"label":"Last day of instruction", "date":"2019-12-06" },
  {"label":"Finals Begin", "date":"2019-12-07" },
  {"label":"Finals End", "date":"2019-12-13" },
  {"label":"Last day to drop (11pm)", "date":"2019-10-23" }
  ]


kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
